website/auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from .models import Student, Tutor, Appointment
from . import db
from werkzeug.security import generate_password_hash,  check_password_hash
from flask_login import login_user, login_required, logout_user, current_user
from . import db
import json
import re
import mimetypes
import base64
import io
from datetime import datetime
import jwt
import requests
from time import time

auth = Blueprint('auth', __name__)

@auth.route('/zoom',methods = ['POST', "GET"])
def zoom():
    decoded_data = 0
    file_type = 0
    appts_Table = request.args.get('appt_Table')
    appt_found = Appointment.query.join(Tutor, Tutor.id == Appointment.tutor_id).filter(
        Appointment.student_id == current_user.get_id())
    # print(current_user.get_id())
    # print(appt_found)
    tutorNames_found = Tutor.query.join(Appointment, Tutor.id == Appointment.tutor_id).filter(
        Appointment.student_id == current_user.get_id()).all()
    # print(tutorNames_found)
    JoinedRows = []
    for appt in appt_found:
        for tutor in tutorNames_found:
            if tutor.id == appt.tutor_id:
                JoinedRows.append(
                    [appt, str(tutor.first_name + ' ' + tutor.last_name)])

    tutor_search = request.args.get('tutor_search')
    if tutor_search:
        tutor_all = Tutor.query.filter(Tutor.first_name.contains(
            tutor_search) | Tutor.last_name.contains(tutor_search) | Tutor.id.contains(tutor_search))
    else:
        tutor_all = Tutor.query.all()

    for tutor in tutor_all:
        user_id = tutor.id
        user_row = Tutor.query.filter_by(id=user_id).first()
        binary_data = user_row.profile_pic
        file_obj = io.BytesIO(binary_data)
        decoded_data = base64.b64encode(file_obj.read()).decode('utf-8')
        file_type, encoding = mimetypes.guess_type(user_row.profile_picname)

    tutor_search = request.args.get('tutor_search')
    if tutor_search:
        tutor_all = Tutor.query.filter(Tutor.first_name.contains(tutor_search) | Tutor.last_name.contains(tutor_search) | Tutor.id.contains(tutor_search))
    else:
        tutor_all = Tutor.query.all()
    API_KEY = 'qecUpEX1SUGYDoNDH22qng'
    API_SEC = 'FZxPYx6U2sBIwJUe3X7Nsr1mzMONgFipllnS'

    token = jwt.encode(
        {'iss': API_KEY, 'exp': time() + 5000},

        API_SEC,
        algorithm='HS256'
    )

    meetingdetails = {"topic": "Online Tutoring Appointment",
                  "type": 2,
                  "start_time": "2019-06-14T10: 21: 57",
                  "duration": "45",
                  "timezone": "Europe/Madrid",
                  "agenda": "test",
 
                  "recurrence": {"type": 1,
                                 "repeat_interval": 1
                                 },
                  "settings": {"host_video": "true",
                               "participant_video": "true",
                               "join_before_host": "False",
                               "mute_upon_entry": "False",
                               "watermark": "true",
                               "audio": "voip",
                               "auto_recording": "cloud"
                               }
                  }
    
    headers = {'authorization': 'Bearer ' + token,
               'content-type': 'application/json'}
    r = requests.post(
        f'https://api.zoom.us/v2/users/me/meetings',
        headers=headers, data=json.dumps(meetingdetails))
 
    y = json.loads(r.text)
    join_URL = y["join_url"]
    meetingPassword = y["password"]
    return render_template("student-home.html", user = current_user, join_URL = join_URL, tutor_all=tutor_all, data=decoded_data, fileType=file_type, appointments=JoinedRows)

@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')

        student = Student.query.filter_by(email=email).first()
        tutor = Tutor.query.filter_by(email=email).first()
        if student:
            if check_password_hash(student.password, password):
                flash('Logged in successfully!', category='success')
                login_user(student, remember=True)
                return redirect(url_for('views.student_home'))
            else:
                flash('Incorrect password, try again.', category='error')
        elif tutor:
            if check_password_hash(tutor.password, password):
                flash('Logged in successfully!', category='success')
                login_user(tutor, remember=True)
                return redirect(url_for('views.tutor_home'))
            else:
                flash('Incorrect password, try again.', category='error')
        else:
            flash('Email does not exist.', category='error')

    return render_template('login.html', user=current_user)


@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('views.index', user=current_user))


@auth.route('/student-registration', methods=['GET', 'POST'])
def student_registration():
    errors = {}
    if request.method == 'POST':
        firstName = request.form.get('firstName')
        lastName = request.form.get('lastName')
        email = request.form.get('email')
        phoneNumber = request.form.get('phoneNumber')
        password = request.form.get('password')
        confirmPassword = request.form.get('confirmPassword')

        studentEmailExists = Student.query.filter_by(email=email).first()
        tutorEmailExists = Tutor.query.filter_by(email=email).first()

        if not (firstName or firstName.isalpha()):
            errors["firstName"] = ["First name required and alphabet only"]
        elif not (lastName or lastName.isalpha()):
            errors["lastName"] = ["Last name required and alphabet only"]
        elif not re.match(r'^[a-zA-Z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,3}$', email):
            errors["email"] = ["Email incorrect format"]
        elif studentEmailExists or tutorEmailExists:
            errors["email"] = ["Email already exists"]
        elif not phoneNumber:
            errors["phoneNumber"] = ["Phone number required"]
        elif not re.match(r'^\d{10}$', phoneNumber):
            errors["phoneNumber"] = [
                "Phone number should be 10 digits no dashes"]
        elif not password:
            errors["password"] = ["Password cannot be empty"]
        elif not re.match(r'^(?=.*[A-Z])(?=.*\d)(?=.*[!@#$%^&*()]).+$', password):
            errors["password"] = ["Password does not follow rules"]
        elif password != confirmPassword:
            errors["confirmPassword"] = ["Passwords do not match"]
        else:
            new_student = Student(first_name=firstName, last_name=lastName, email=email,
                                  password=generate_password_hash(
                                      password, method='sha256'),
                                  phone_number=phoneNumber, total_hours=0, fav_tutors='')
            db.session.add(new_student)
            db.session.commit()
            login_user(new_student, remember=True)
            flash('Account created!', category='success')
            return redirect(url_for('views.student_home'))
    return render_template('student-registration.html', user=current_user, errors=errors)


@auth.route('/tutor-registration', methods=['GET', 'POST'])
def tutor_registration():
    errors = {}
    if request.method == 'POST':
        firstName = request.form.get('firstName')
        lastName = request.form.get('lastName')
        email = request.form.get('email')
        phoneNumber = request.form.get('phoneNumber')
        password = request.form.get('password')
        confirmPassword = request.form.get('confirmPassword')
        subject = json.dumps(request.form.getlist('subject'))
        days = json.dumps(request.form.getlist('day'))
        mondayTime = json.dumps(request.form.getlist('mondayTime'))
        tuesdayTime = json.dumps(request.form.getlist('tuesdayTime'))
        wednesdayTime = json.dumps(request.form.getlist('wednesdayTime'))
        thursdayTime = json.dumps(request.form.getlist('thursdayTime'))
        fridayTime = json.dumps(request.form.getlist('fridayTime'))
        saturdayTime = json.dumps(request.form.getlist('saturdayTime'))
        sundayTime = json.dumps(request.form.getlist('sundayTime'))
        profilePic = request.files['file']
        profilePicName = profilePic.filename
        about = request.form.get('about')

        studentEmailExists = Student.query.filter_by(email=email).first()
        tutorEmailExists = Tutor.query.filter_by(email=email).first()

        if not (firstName or firstName.isalpha()):
            errors["firstName"] = ["First name required and alphabet only"]
        elif not (lastName or lastName.isalpha()):
            errors["lastName"] = ["Last name required and alphabet only"]
        elif not re.match(r'^[a-zA-Z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,3}$', email):
            errors["email"] = ["Email incorrect format"]
        elif studentEmailExists or tutorEmailExists:
            errors["email"] = ["Email already exists"]
        elif not phoneNumber:
            errors["phoneNumber"] = ["Phone number required"]
        elif not re.match(r'^\d{10}$', phoneNumber):
            errors["phoneNumber"] = [
                "Phone number should be 10 digits no dashes"]
        elif not password:
            errors["password"] = ["Password cannot be empty"]
        elif not re.match(r'^(?=.*[A-Z])(?=.*\d)(?=.*[!@#$%^&*()]).+$', password):
            errors["password"] = ["Password does not follow rules"]
        elif password != confirmPassword:
            errors["confirmPassword"] = ["Passwords do not match"]
        elif not about:
            errors["about"] = ["About section required"]
        elif not re.match(r'^[a-zA-Z0-9.\s]*$', about):

website/templates/appt-created.html
{% extends "base.html" %} {% block head %}
<meta http-equiv="X-UA-Compatible" content="IE=edge" />
{% endblock %} {% block title %}Registration Complete{% endblock %} {% block
body_content %}
<body class="bg-dark">
  <div class="container">
    <div class="row mt-5">
      <div
        class="col-lg-5 bg-white m-auto shadow p-4 mt-5 mb-5 bg-white rounded"
      >
        <h1 class="text-center pt-3 mb-4">Appointment Created!</h1>
        <div class="text-center">
          <a
            href="/"
            class="btn btn-primary btn-xl text-uppercase pe-auto mt-4"
          >
            Return to Homepage
          </a>
        </div>
      </div>
    </div>
  </div>
  <script src="../static/js/scripts.js"></script>
</body>
{% endblock %}

website/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="../static/assets/favicon.ico" />
    <!-- Font Awesome icons (free version)-->
    <script
      src="https://use.fontawesome.com/releases/v6.1.0/js/all.js"
      crossorigin="anonymous"
    ></script>
    <!-- Google fonts-->
    <link
      href="https://fonts.googleapis.com/css?family=Montserrat:400,700"
      rel="stylesheet"
      type="text/css"
    />
    <link
      href="https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700"
      rel="stylesheet"
      type="text/css"
    />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="../static/css/styles.css" rel="stylesheet" />
    {% block head %} {% endblock %}
    <title>{% block title %}Classroom Connect{% endblock %}</title>
  </head>
  {% block body_tag %}
  <body id="page-top">
    {% endblock %}
    <nav class="navbar navbar-expand-lg navbar-dark fixed-top" id="mainNav">
      <div class="container">
        <a class="navbar-brand" href="/"
          ><img src="../static/assets/img/navbar-logo.svg" alt="..."
        /></a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarResponsive"
          aria-controls="navbarResponsive"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          Menu
          <i class="fas fa-bars ms-1"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav text-uppercase ms-auto py-4 py-lg-0">
            <li class="nav-item">
              <a class="nav-link" href="#services">Services</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#portfolio">Subjects</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#team">Tutors</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('views.make_appointment') }}">Make an Appointment</a>
            </li>
            {% if not user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('auth.login') }}">Log In</a>
            </li>
            <li class="nav-item dropdown">
              <a
                class="btn btn-dark dropdown-toggle"
                role="button"
                id="dropdownMenuLink"
                data-bs-toggle="dropdown"
                aria-expanded="false"
              >
                Register
              </a>
              <div class="dropdown-menu dropdown-menu-dark">
                <a
                  href="{{ url_for('auth.student_registration') }}"
                  class="dropdown-item"
                  >As a Student</a
                >
                <div class="dropdown-divider"></div>
                <a
                  href="{{ url_for('auth.tutor_registration') }}"
                  class="dropdown-item"
                  >As a Tutor</a
                >
              </div>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('auth.logout') }}">Log Out</a>
            </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>

    {%block body_content %} {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <script src="../static/js/scripts.js"></script>
    <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
    <!-- * *                               SB Forms JS                               * *-->
    <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
    <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
    <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
  </body>
</html>

website/templates/index.html
{% extends "base.html" %}

    {% block body_content %}
    <!-- Masthead-->
    <header class="masthead">
        <div class="container">
            <div class="masthead-subheading">Welcome to our tutoring website!</div>
            <div class="masthead-heading text-uppercase">Classroom Connect</div>
            <a class="btn btn-primary btn-xl text-uppercase" href="#services">Get Started</a>
        </div>
    </header>
    <!-- Services-->
    <section class="page-section" id="services">

      <div class="container">
        <div class="text-center">
          <h2 class="section-heading text-uppercase">Services</h2>
          <h3 class="section-subheading text-muted">What we can do for you!</h3>
        </div>
        <div class="row text-center">
          <div class="col-md-4">
            <span class="fa-stack fa-4x">
              <i class="fas fa-circle fa-stack-2x text-primary"></i>
              <i class="fas fa-shopping-cart fa-stack-1x fa-inverse"></i>
            </span>
            <h4 class="my-3">Get Connected</h4>
            <p class="text-muted">Get access to a world wide group of experts waiting to assist your studies.</p>
          </div>
          <div class="col-md-4">
            <span class="fa-stack fa-4x">
              <i class="fas fa-circle fa-stack-2x text-primary"></i>
              <i class="fas fa-lock fa-stack-1x fa-inverse"></i>
            </span>
            <h4 class="my-3">Find a tutor</h4>
            <p class="text-muted">Find favorite tutors specific to your needs and learning style.</p>
          </div>
          <div class="col-md-4">
            <span class="fa-stack fa-4x">
              <i class="fas fa-circle fa-stack-2x text-primary"></i>
              <i class="fas fa-laptop fa-stack-1x fa-inverse"></i>
            </span>
            <h4 class="my-3">Make an appointment</h4>
            <p class="text-muted">Schedule personal tutoring appointments with your favorite tutors today!</p>
          </div>
        </div>
      </div>
    </section>
    <!-- Subjects Grid-->
    <section class="page-section bg-light" id="portfolio">
      <div class="container">
        <div class="text-center">
          <h2 class="section-heading text-uppercase">Subjects</h2>
          <h3 class="section-subheading text-muted"></h3>
        </div>
        <div class="row">
          <div class="col-lg-4 col-sm-6 mb-4">
            <!-- Portfolio item 1-->
            <div class="portfolio-item">
              <a class="portfolio-link" data-bs-toggle="modal" href="#portfolioModal1">
                <div class="portfolio-hover">
                  <div class="portfolio-hover-content"><i class="fas fa-plus fa-3x"></i></div>
                </div>
                <img class="img-fluid" src="../static/assets/img/portfolio/6.jpg" alt="..." />
              </a>
              <div class="portfolio-caption">
                <div class="portfolio-caption-heading">Math</div>
              </div>
            </div>
          </div>
          <div class="col-lg-4 col-sm-6 mb-4">
            <!-- Portfolio item 2-->
            <div class="portfolio-item">
              <a class="portfolio-link" data-bs-toggle="modal" href="#portfolioModal2">
                <div class="portfolio-hover">
                  <div class="portfolio-hover-content"><i class="fas fa-plus fa-3x"></i></div>
                </div>
                <img class="img-fluid" src="../static/assets/img/portfolio/5.jpg" alt="..." />
              </a>
              <div class="portfolio-caption">
                <div class="portfolio-caption-heading">Science</div>
              </div>
            </div>
          </div>
          <div class="col-lg-4 col-sm-6 mb-4">
            <!-- Portfolio item 3-->
            <div class="portfolio-item">
              <a class="portfolio-link" data-bs-toggle="modal" href="#portfolioModal3">
                <div class="portfolio-hover">
                  <div class="portfolio-hover-content"><i class="fas fa-plus fa-3x"></i></div>
                </div>
                <img class="img-fluid" src="../static/assets/img/portfolio/4.jpg" alt="..." />
              </a>
              <div class="portfolio-caption">
                <div class="portfolio-caption-heading">English</div>
              </div>
            </div>
          </div>
          <div class="col-lg-4 col-sm-6 mb-4 mb-lg-0">
            <!-- Portfolio item 4-->
            <div class="portfolio-item">
              <a class="portfolio-link" data-bs-toggle="modal" href="#portfolioModal4">
                <div class="portfolio-hover">
                  <div class="portfolio-hover-content"><i class="fas fa-plus fa-3x"></i></div>
                </div>
                <img class="img-fluid" src="../static/assets/img/portfolio/3.jpg" alt="..." />
              </a>
              <div class="portfolio-caption">
                <div class="portfolio-caption-heading">History</div>
              </div>
            </div>
          </div>
          <div class="col-lg-4 col-sm-6 mb-4 mb-sm-0">
            <!-- Portfolio item 5-->
            <div class="portfolio-item">
              <a class="portfolio-link" data-bs-toggle="modal" href="#portfolioModal5">
                <div class="portfolio-hover">
                  <div class="portfolio-hover-content"><i class="fas fa-plus fa-3x"></i></div>
                </div>
                <img class="img-fluid" src="../static/assets/img/portfolio/2.jpg" alt="..." />
              </a>
              <div class="portfolio-caption">
                <div class="portfolio-caption-heading">Engineering</div>
              </div>
            </div>
          </div>
          <div class="col-lg-4 col-sm-6">
            <!-- Portfolio item 6-->
            <div class="portfolio-item">
              <a class="portfolio-link" data-bs-toggle="modal" href="#portfolioModal6">
                <div class="portfolio-hover">
                  <div class="portfolio-hover-content"><i class="fas fa-plus fa-3x"></i></div>
                </div>
                <img class="img-fluid" src="../static/assets/img/portfolio/1.jpg" alt="..." />
              </a>
              <div class="portfolio-caption">
                <div class="portfolio-caption-heading">Computer Science</div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
    <!-- Team-->
    <section class="page-section bg-light" id="team">
      <div class="container">
        <div class="text-center">
          <h2 class="section-heading text-uppercase">Our Tutors</h2>
          <h3 class="section-subheading text-muted">Find your favorite tutor!</h3>
        </div>
       
        <!--Search formating-->
        <div class="tutor-search">
            <form class="form-inline my-2 my-lg-0" method="GET" action="" style="margin:auto">
                <input class="tutor-search-bar" type="search" placeholder="Search Tutor by name, ID, or subject" name="tutor_search">
                <button class="tutor-search-btn" type="submit"><i class="fas fa-search"></i></button>
            </form>
        </div>
        <!--display all and search-->
        <div class="row" style="line-height: 5em; overflow:auto; margin: auto; height:1100px" >
            {% for tutor in tutor_all %}
                <div class="col-lg-4">
                    <div class="team-member">
                        <div class="Tutors">
                            {% if fileType == 'image/png' %}
                            <img src="data:image/png;base64,{{ data }}" alt="File" style="width:auto; height:300px; border-radius:20%">
                            {% elif fileType == 'image/jpeg' %}
                            <img src="data:image/jpeg;base64,{{ data }}" alt="File" style="width:auto; height:300px; border-radius:20%">
                            {% else %}
                            <p>Cannot load image</p>
                            {% endif %}
                            <b><h2 class="name">{{tutor.first_name}} {{tutor.last_name}}</h2></b>
                            <h3>{{tutor.id}}</h3>
                            <h3 style="font-weight:normal">Subjects: </h3>
                              <p style="font-weight:normal">{{tutor.subjects}}</p>
                            <h3 style="font-weight:normal">Availability: </h3>
                              <p align="left" style="margin-left:95px; font-weight:normal">Monday: {{tutor.monday_time}}</p>
                              <p align="left" style="margin-left:95px; font-weight:normal">Tuesday: {{tutor.tuesday_time}}</p>
                              <p align="left" style="margin-left:95px; font-weight:normal">Wednesday: {{tutor.wednesday_time}}</p>
                              <p align="left" style="margin-left:95px; font-weight:normal">thursday: {{tutor.thursday_time}}</p>
                              <p align="left" style="margin-left:95px; font-weight:normal">Friday: {{tutor.friday_time}}</p>
                              <p align="left" style="margin-left:95px; font-weight:normal">Saturday: {{tutor.saturday_time}}</p>
                              <p align="left" style="margin-left:95px; font-weight:normal">Sunday: {{tutor.sunday_time}}</p>
                            <h3 style="font-weight:normal">Total Tutor Hours: {{tutor.total_hours}}</h3>
                            <h3 style="font-weight:normal">Bio: </h3>
                              <p style="font-weight:normal">{{tutor.bio}}</p>
                        </div>
                    </div>
                </div>
             {% endfor %}
          </div>
        </div>
      </div>
        <div class="row">
          <div class="col-lg-8 mx-auto text-center">
            <p class="large text-muted">Want to help your fellow peers? <a href="{{ url_for('auth.tutor_registration') }}">Sign up</a> to be a tutor today!</p>
          </div>
        </div>
      </div>
    </section>
   
    <!-- Footer-->
    <footer class="footer py-4">
      <div class="container">
        <div class="row align-items-center">
          <div class="col-lg-4 text-lg-start">Copyright &copy; UTD 2023</div>
          <div class="col-lg-4 my-3 my-lg-0">
            <a class="btn btn-dark btn-social mx-2" href="#!" aria-label="Twitter"><i class="fab fa-twitter"></i></a>
            <a class="btn btn-dark btn-social mx-2" href="#!" aria-label="Facebook"><i class="fab fa-facebook-f"></i></a>
            <a class="btn btn-dark btn-social mx-2" href="#!" aria-label="LinkedIn"><i class="fab fa-linkedin-in"></i></a>
          </div>
          <div class="col-lg-4 text-lg-end">
            <a class="link-dark text-decoration-none me-3" href="#!">Privacy Policy</a>
            <a class="link-dark text-decoration-none" href="#!">Terms of Use</a>
          </div>
        </div>
      </div>
    </footer>
  {% endblock %}
</html>

website/templates/login.html
{% extends "base.html" %} {% block title %}Login{% endblock %} {% block body_tag %}
<body class="bg-dark">
  {% endblock %} {%block body_content %}
  <div class="container">
    <!-- <a href="/" class="btn btn-outline-warning btn-lg text-uppercase pe-auto mt-4">
        <i class="fa fa-arrow-left" aria-hidden="true"></i>
        Go Back
      </a> -->
    <div class="row mt-5">
      <div class="col-lg-5 bg-white m-auto shadow p-4 mt-5 mb-5 bg-white rounded">
        <h2 class="text-center pt-3 mb-4">Log In</h2>
        <form method="POST" enctype="multipart/form-data">
          <div class="input-group mb-4">
            <span class="input-group-text"><i class="fa fa-envelope"></i></span>
            <input
              type="email"
              class="form-control"
              name="email"
              placeholder="Email@example.com"
              pattern="[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,3}$"
              title="example@example.example"
              required
            />
          </div>
          <div class="input-group mb-4">
            <span class="input-group-text"><i class="fa fa-lock"></i></span>
            <input type="password" class="form-control" name="password" placeholder="Password" required />
          </div>

          <div class="text-center mb-4">
            <input class="btn btn-primary btn-xl text-uppercase pe-auto" type="submit" value="Log In" />
          </div>
          <p class="text-center">
            Don't have an account?<br />
            Register as a: <br />
            <a href="{{ url_for('auth.student_registration') }}">Student</a><br />
            <a href="{{ url_for('auth.tutor_registration') }}">Tutor</a>
          </p>
        </form>
      </div>
    </div>
  </div>
  {% endblock %}
</body>

website/templates/student-registration.html
{% extends "base.html" %} {% block head %}
<meta http-equiv="X-UA-Compatible" content="IE=edge" />
{% endblock %} 
{% block title %}Student Registration{% endblock %} 

{% block body_tag %}
<body class="bg-dark">
  {% endblock %} 
  
  {% block body_content %}
  <div class="container">
    <a href="/" class="btn btn-outline-warning btn-lg text-uppercase pe-auto mt-4">
      <i class="fa fa-arrow-left" aria-hidden="true"></i>
      Go Back
    </a>
    <div class="row mt-5">
      <div class="col-lg-5 bg-white m-auto shadow p-4 mb-5 bg-white rounded">
        <h2 class="text-center pt-3 mb-4">Student Registration</h2>
        <!-- Start of Form -->
        <form method="POST" enctype="multipart/form-data">
          <!-- Account information -->
          {% for e in errors["firstName"] %}
          <div class="text-danger">{{e}}</div>
          {% endfor %}
          <div class="input-group mb-4">
            <span class="input-group-text"><i class="fa fa-user"></i></span>
            <input type="text" class="form-control" name="firstName" placeholder="First Name" required />
          </div>
          {% for e in errors["lastName"] %}
          <div class="text-danger">{{e}}</div>
          {% endfor %}
          <div class="input-group mb-4">
            <span class="input-group-text"><i class="fa fa-user"></i></span>
            <input type="text" class="form-control" name="lastName" placeholder="Last Name" required />
          </div>
          {% for e in errors["email"] %}
          <div class="text-danger">{{e}}</div>
          {% endfor %}
          <div class="input-group mb-4">
            <span class="input-group-text"><i class="fa fa-envelope"></i></span>
            <input
              type="email"
              class="form-control"
              name="email"
              placeholder="Email@example.com"
              pattern="[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,3}$"
              title="example@example.example"
              required
            />
          </div>
          {% for e in errors["phoneNumber"] %}
          <div class="text-danger">{{e}}</div>
          {% endfor %}
          <div class="input-group mb-4">
            <span class="input-group-text"><i class="fa fa-phone"></i></span>
            <input
              type="tel"
              class="form-control"
              name="phoneNumber"
              placeholder="Phone ex: 1234567890"
              pattern="[0-9]{10}"
              title="Only 10 Numbers"
              required
            />
          </div>
          {% for e in errors["password"] %}
          <div class="text-danger">{{e}}</div>
          {% endfor %}
          <div class="input-group mb-2">
            <span class="input-group-text"><i class="fa fa-lock"></i></span>
            <input
              id="studentPassword"
              type="password"
              class="form-control"
              name="password"
              placeholder="Password"
              onkeyup="validateStudent()"
              required
            />
          </div>
          <ul class="requirements">
            <li id="upperCheckS">Must have an uppercase character</li>
            <li id="numberCheckS">Must have a number</li>
            <li id="specialCheckS">Must have a special character !@#$%^&*()</li>
          </ul>
          {% for e in errors["confirmPassword"] %}
          <div class="text-danger">{{e}}</div>
          {% endfor %}
          <div class="input-group mb-4">
            <span class="input-group-text"><i class="fa fa-lock"></i></span>
            <input type="password" class="form-control" name="confirmPassword" placeholder="Confirm Password" required />
          </div>

          <!-- Register Button -->
          <div class="text-center mb-4">
            <input class="btn btn-primary btn-xl text-uppercase pe-auto" type="submit" value="Sign Up" />
          </div>
          <p class="text-center">Already have an account? Log In <a href="{{ url_for('auth.login') }}">Here</a></p>
        </form>
      </div>
    </div>
  </div>
  {% endblock %}